### ISSUE TITLE
Alternative config storage

### ISSUE THREAD

**Issue by agoalofalife** [ash-jc-allen/laravel-config-validator#51]
Hi! First of all I want to say thanks so much your job and this package.
I have a problem with path configuration data.
By default laravel storage data 'config' path, it's ok for everyone, but in my case complicated.
I want to set data another path
For example 'app/Configuration/...' 
I suggest changing hydrateConfigValueArray or another part codes.
Inject some interface for storing configuration data, which knows how get any values.
What do you think about this thought?
I will make PR, if you like this idea.

**Comment by ash-jc-allen** [comment]
Hey! Thanks for the kind words!

Just to give me a bit more context, could you give me a barebones example of:

- Where you would be storing your config files
- How you would be calling the config in your app's code

If you can do that, I'll have a tinker and see if I can find a nice solution for it 😄

**Comment by agoalofalife** [comment]
Unfortunately I don't use the standard helper `config`
Values ​​from config files are obtained using special classes
The idea is to be independent of the path and possibly the storage type of the configuration data.
I can suggest two levels of abstraction

**First level**
You can add the ability to add your path to the configuration data, (mine look exactly the same as in Larvel, just arrays)

**Second level**
Not just depending on files, you can store configurations anywhere (database, file, etc.) and have a repository that knows how to get this data.

As long as the first level is enough for me

In simple words, I want to transfer files not from the standard laravel folder

`And yet, it seems to me that the file validation function should not depend much on the location of these files and the way they are retrieved (although this certainly makes sense for Laravel)`

**Comment by ash-jc-allen** [comment]
Unfortunately, I think I'll hold off on making any changes like this, sorry. I think it'd add extra complexity that I'd have to maintain.

I think for most projects using this, the config would typically be accessible using the `config` helpers, so it's suitable for the majority of use cases.

But, if it's something that a lot of people might want, then I'd be open to maybe taking a look at it 🙂
